# -*- coding: utf-8 -*-
"""SPINEXvDONE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LL_8PBKh7esCr8uaGg3M41s3x3CFYE4u
"""

!pip install SPINEX

from SPINEX import SPINEXClassifier

classifier = SPINEXClassifier(
    n_neighbors=20,
    distance_threshold=0.05,
    distance_threshold_decay=0.95,
    ensemble_method='stacking',
    metric='manhattan'
)

import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X, y = make_classification(n_samples=100, n_features=20, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

from SPINEX import SPINEXRegressor

Regressor = SPINEXRegressor(n_neighbors=5, distance_threshold=0.5,
                 distance_threshold_decay=0.95, ensemble_method= 'boosting',
                 n_features_to_select=None, auto_select_features=False,
                 use_local_search=False, prioritized_features=None,
                 missing_data_method='mean_imputation', outlier_handling_method='z_score_outlier_handling',
                 exclude_method='zero')

import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X, y = make_regression(n_samples=2, n_features=20, n_targets=1, noise=0.1, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
Regressor.fit(X_train, y_train)
y_pred = Regressor.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Test MSE:", mse)